# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tree_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileSystemModel,QTreeView,QVBoxLayout,QPushButton,QInputDialog,QLineEdit


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.path="C:"


        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 300, 431, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 431, 31))
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(30, 250, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        font1 = QtGui.QFont()
        font1.setPointSize(10)
        self.label1.setFont(font1)
        self.label1.setObjectName("label")



        self.treeWidget=QTreeView(self)
        self.treeWidget.setColumnWidth(0,100)
        self.treeWidget.setGeometry(QtCore.QRect(30, 130,300, 120))
        self.treeWidget.setObjectName("treeWidget")

        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 80, 321, 151))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 90, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 150, 91, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")




        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)



        self.model=QFileSystemModel()
        self.model.setRootPath(self.path)
        self.treeWidget.setModel(self.model)
        self.treeWidget.setColumnWidth(0, 200)
        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.start) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.quit) # type: ignore

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ASX 사이트 크롤링 프로그램(REV02 220603)"))
        self.groupBox.setTitle(_translate("MainWindow", "저장경로"))
        self.pushButton.setText(_translate("MainWindow", "시작"))
        self.pushButton_2.setText(_translate("MainWindow", "종료"))
        self.label1.setText(_translate("MainWindow", "※ 대상 폴더를 선택하세요(폴더ONLY)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
